// Copyright 2026 Scrakk Studio
// SPDX-License-Identifier: Apache-2.0
// Licencia completa en LICENSE (Apache License 2.0).

/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Asegura índice trigram para `root`. Devuelve path del índice como string.
 * No falla si el build falla: el caller hace fallback a scan.
 */
export declare function ensureIndex(root: string): string
export declare function indexStatus(root: string): string
/** Empieza a vigilar `root` (idempotente). Rebuild a los ~2s de quietud. */
export declare function watchRoot(root: string): string
/** Deja de vigilar `root`. */
export declare function unwatchRoot(root: string): string
/**
 * Búsqueda de archivos por nombre (substring case-insensitive).
 * Usa `ignore` (misma semántica gitignore que kolargrep) — rápida sin índice.
 * Devuelve JSON: [{path,name,isDirectory}]
 */
export declare function searchFiles(root: string, query: string, maxResults?: number | undefined | null): string
/**
 * Grep con índice trigram + verificación regex en paralelo.
 * Devuelve JSON: [{file,line,content,preview}]
 */
export declare function grepFiles(root: string, pattern: string, caseSensitive?: boolean | undefined | null, maxResults?: number | undefined | null): string
