export { Titlebar } from './Titlebar'
export { useWindowControls } from './hooks/useWindowControls'
export { MenuBar } from './components/MenuBar/MenuBar'
export { WidgetContainer } from './widgets/WidgetContainer'
export { getTitlebarWidgets, TITLEBAR_WIDGET_REGISTRY } from './widgets/registry'
export type { TitlebarWidgetEntry } from './widgets/registry'
